# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'Cidh2NLiJGVRmHrqgD4woWhMHkl3krlb'
  redis: 'PBX6Qmg8CeJ8qBRNwm-NtIaOVAW7b_D8'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'aBvH2xtlQqI0dmI7d_2j_p5gufZEJBl8'

  emailSecretHashPepper: 'yIfNVsfTU2HwD3VyzUPIDIyjVr8AwFxA'
  jwtHmacSha512PrivateKey: 'ywiJkaAYTn2832_clJX7K76rQfnnhnDp'
  jwtRefreshTokenHashPepper: 'hPcy1Vp0FFpC9ncP2liwx2xnCH_2hHV_'
  # serverSideSessionKeyHashPepper: 'Wu2Go8tIVkx4_Q3SRgjwMguqxtGoUhNN'

test:
  database: 'aLctqL238y4wvGwyfEPx8jNJHE0Tl7mz'
  redis: 'HMP-L0wr0XR6ZAxvo_knBaforrLJOKia'

  emailSecretHashPepper: '2msMH1cl6ChGwDhk5rmqN9RpINXB0glo'
  jwtHmacSha512PrivateKey: 'Gee_cTWEcxRglTuGejVdg1cJeeQE_mFL'
  jwtRefreshTokenHashPepper: 'hIsnqGPvLXUM_DpyCmPuHthASv2DUUXH'
  # serverSideSessionKeyHashPepper: 'K6IRPQw_oJhIJMwZAQTxqupxJj36EHua'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'C1u8hldr0xyDm-w--TuYacVwegklzKv5'
  serviceSecret: 'QAzw45GrZqhchlZ6zFmXCy2X2_4Q7l4r'

  emailSecretHashPepper: '7d09fIkUw2i8OG_16mGdvVEbYuGWV-Fi'
  jwtHmacSha512PrivateKey: 'g4qgNi0vxAcjQ7T8Nl5Id07NYluIcd_6'
  jwtRefreshTokenHashPepper: '_uG72qPE4BW-CqTeAeQ5AaT47O-Onjtc'
  # serverSideSessionKeyHashPepper: '22LUnkrllVzpvSjPj0mcbc-4zkJimbVh'

# Passwords used in production mode.
production:
  database: 'YA0G_RRmuHGZ4wdalQr2QllshEvSJD2-'
  serviceSecret: '2hXm5eWKclBzTn1HwLQlyjq6TpRT7R4h'

  emailSecretHashPepper: '4V498yQgBAPuZrM6gwIeCBANU9JSGXI8'
  jwtHmacSha512PrivateKey: '7dRvGuecPmFl6TtbibXK8jQ1qo8VYiKz'
  jwtRefreshTokenHashPepper: 'eK6_tyc9cCsDXQmzr6fJTO0nYYySWO6y'
  # serverSideSessionKeyHashPepper: 're3CZ3TxK2zCMUlLj41HmUqE5J4My_wO'
